# -*- coding: utf-8 -*-
"""
Created on Tue May 19 21:01:47 2015

@author: Harrison
"""

import ctypes

# Define constants
SW_MAXIMIZE = 3
HWND_TOP = ctypes.windll.user32.GetForegroundWindow()

# Define ShowWindow function from user32.dll
ctypes.windll.user32.ShowWindow(HWND_TOP, SW_MAXIMIZE)


print("""

WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNNNNNNNN
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNNNNNNNN
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNNNNNNNN
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNNNNNNNN
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNNNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNNNNNNNNNN
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNNNNNNNNNNN
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNNNNNNNNNNN
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNNNNNNNNNNN
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNNNNNNNN
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNWWWWWWWWWWWWWNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNNNNNNNN
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNNNNNNNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNNNNNNNN
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNNNWWWWWNNNNNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNNNNNNNN
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNNNWWWWWWWWWWWNNWWWWWWWWWWWWWNWWWWWWWWWWNWWWWWWNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNNNNNNNN
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNWWWNNNWWWNNWWWNWWNNWWWWWWNNNNWWWWWWWWNNNNNNNNNWWWWWWWWNNNNNNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNNNNNNNN
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNNNNNNNNNNNNNNNNNNNNNNNWNKkkxkO0KKXXXXXXXKKXXKKKXXXXNNNNXKKKKKXXNNNNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNNNNNNNN
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNNNNNNNNNNNNNNNNNNXK0000ko:,''',;:cldkOOOO0OOOOOkOOOK00K000OO000KKKKXXNNKKNWWNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNNNNNNNN
NNNNWWWWNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNWWNNNNNNNNNNNNNXK000Oxlc;;;,',,,''',,:dxxkOOkdxkkkkxdxxxkdccoxxxolldk0K000OOOOOOKWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNNNNNNNNN
NNNNWWWWNNWWWNNNNNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNNNNNNNNX0Okkkxoolcc:,;:;;;,..,,,:loxdloxkkkkkddOOkxxxxkdc:;,:dOOOko;ckOOOkk000KOx0NNNNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNNNNNNNNNN
WWWNNNNNNNWWWNNNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNNNNNNNNNWNNNXKKOo:,''''',:::;'.,;:;;::cc;:xOOOOkc:dxxkx:;loc;:loc;,,,,:xkOOOOdcdOOOkxkOOkkkOO0KXNWWNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNNNNNNNNNN
WWWNNNNNNNWWWNNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNNNNNNNNNNXKKOkdl;......'.',;,'..',',oOOOOocx0Okkxlc:;;;,''',,;,,'',;,,,;cdxkkxl::loodxxkkdokK0kkXNNNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNNNNNNNNNN
NNWWWNNNNNNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNNNNNNNWWNNNNNNXXKOkkd:,'......''...''....',;oxkOOo:;cllodkOkxl,..,loxkxl;,;;;;,;lxdddccloc:;cxkkOOolxOO0KKXXNNNWWWWWWWNWWWWWWWWWWWWWWWWWWWWWWWNNNNNNNNNN
NNNWWWWNNNNNWWWNNNWWWWWWWWWWWWWWNNWWWWWWWWWWWWWNNNNNNNNNNNNXX00OOko:'''.......,;:;......,okxxl:oxxxlc;'lO000OOd;';dkkkkdlodxdoodkkkkkdxkkkxo:cdxkkolxkkOKKXXXNWWWWNWWWWWWWWWWWWWWWWWWWWWWWWWWNNNNNNNNNNN
NNNWWWWNNNNNWWWNNNWWWWWWWWWWWWNNNNNWWWWWWWWWWWWWWNNNNNNNNNNXK0Odoc,....',cc;.,okkdl,..,':dxkkookO0OOkd;;okkkkxolc:coxxkocxkkOkkxxkxxddxOOOOxl;lxkxdxO0kdlokKKKNNNWWWWWWWWWWWWWWWWWWWWWWWWWWWWNNNNNNNNNNN
NNNWWWWNNNNNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNNNNNNNNNXKOkxdl,.....:oxkOklcxkxddc;coolc::;,cxxxkkko'..,;:codxxxdcccccldxkOOkxdoooodk0OOkko:lkkkkddxxl,,:o0KXXXNWWWWWWWWWWWWWWWWWWWWWWWWWWWNNNNNNNNNNN
NNNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNNNNNNNNNNNXK0kkxc;'.....:xOkOkdlcoddoccokkkOx:'..'lOOkxxo;';cloodxxkkkxc,cdddodxxddl:;,;okOOOOxc.,oxxdlccc,.'',l0NNXNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNNNNNNNN
NNNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNNNNNNNNNNNNNXOkxl:,'......':xO0Oxloxkkkxlcoxxkkxc...'lk00kkxl;okkkdlddxxxdloxl,;::cdkOxc''',;clll:....,,'.......'.'oKXKXNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNNNNNNNN
NNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNNNNNNNNNNNNNNNNNKOkdl;,'..........;col;cxO000Od:;::cc:',coolcdOkkkl',::;..';cldddxxoccll;lOKOo:;;,''.'....   .........'.'lOXKXNNWWWWWWWWWWWWWWWWWWWWWWWWWWWWNNNNNNNN
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNNNNNNNNNNNNNNNNXOdlol;,,'''''.'''.......;dxxxxdc;lolc,.:dxxxl'';::;.. .......,okkkkkkdldxllOKOdxkdc;,....................,dKXXXNNNWWWWWWWWWWWWWWWWWWWWWWWWWWWNNNNNNNN
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNNNNNNNNNNNNNNXOxolc:,,,'',,,,;;;;;,'.....,;;:c;.:ddxdo;'',;'................ ,dxxkkkkdcokddO0xokOOd:,'.................''oKXXXXNWWWWWWWWWWWWWWWWWWWWWWWWWWWNNNNNNNNNN
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNNNNNNNNNNNNNNNOolc;,'.',,,;;;:c:;;;'.....'',;lol,'codddc'....',,;;,,''....... .;lodddo:;lxxoclolool:;,'................',ck0KXXXNNWWWWWWWWWWWWWWWWWWWWWWWWWNNNNNNNNNNN
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNNNNNNNNNNNNNXKOdl:,'.'''''',,,;;,'......:oddoll:;;::lll:...';:::::;,,.........  ..''''...,;:,';cllc;',,,'...............'ckKKKNXXNWWWWWWWWWWWWWWWWWWWWWWWWWWNNNNNNNNNNN
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNNNNNNNNNNNNNKkdl:,''..........'''....  .;odxkkxdc,;c:,''.',;::::;;,'''''...........''.'''''',,'''',,,,,''...............':xKXKXNXXNWWWWWWWWWWWWWWWWWWWWWWWWWWNNNNNNNNNNN
WWWWWWWWWWWWWWWWWWWWWWWWNNNNNNNNNNNNNNNNNXXkolc:,'''......',,;:::ccc;...';:cloodc....'',;:;;;;,;;;,,;;;;,,''','',,,''''''''.........'..................'ck0XXKXNNNNWWWWWWWWWWWWWWWWWWWWWWWWWNNNNNNNNNNNN
WWWWWWWWWWWWWWWWWWWWWWWWWNNNNNNNNNNNNNNNX0xlc:,''''.....,clcclllc:lxxooolcllcc:,'...',::;:;;;;;:::;;:;;::;,,,''''............',,,;;:::;;;;,,'..........l0KKXNNNNNWWWWWWWWWWWWWWWWWWWWWWWNNNNNNNNNNNNNNNN
WWWWWWWWWWWWWWWWWWWWWWWWWWWWNNNNNNNNNNNN0xl:;,''.......;oolcldo:;;cdxxddodxkxxo;,;,,::::;::c:::::;,''''''.........',:cccllllllooolllllolodxkd:;;,,,,..'xK0KXNWNWWWWWWWWWWWWWWWWWWWWWWWWWNNNNNNNNNNNNNNNN
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNNNNNNNNXkocc:,'.......'lollool;,:col:::;:ldxxdddddoc;:::ccc:;;,''....  ....''''',cdkOOOOkkkxdddooooooddlloxOkxxlccloc,,xKKNNNNWWWWWWWWWWWWWWWWWWWWWWWWWWNNNNNNNNNNNNNNNN
WWWWWNNWWWWWWWWWWWWWWWWWWWWWWWWNNNNNNNNKxoc:,..........;lodol;..,;cllc::ll::cdkkkkxc,;;;;;,,.....'',;;:clodddolllloodxddddxxxxxkkkkxkxdlodkOkkOOxollc;:kXNNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNNNNNNNNNNNNN
WWWWWNNWWWWWWWWWWWWWWWWNNNNNNNNNNNNNNNNKxo::,...........,cll:......,:::llc;..,lxkdc'.,''..'',;clddxkkkkkOOOOOO00OOkkxxxdoollodxkkkkkkxxdxkkkxkOkO0OdldOXNNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNNNNNNNNNNNNN
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNNNNNNNNXOlcl,...........',;:,......;cldxc......','....';:loxkkOOO00000000000KKKKKKKKKK000OkdollodxxkkkkOOOxxxkkxdO0klc0NNNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNNNNNNNNNNNNN
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNNNNNNNNNKdcc,.............','...  'coxOOl..'.','..,;:lxkkOO00KKKKKKKKKKKXXXXXXXXKKKKKKKKKKKK0koccloxOOOOOOkkkkxdxO00l;kNNNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNNNNNNNNNNNNN
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNNNNNNNNNXOoc,.................... .,cloc'.....';:ldkkOO00KKKKXXXXXXXXXXXXXXXXXXXXXKKKKKKKKKKK0Odllok00OOOkkkxddxOkO0d:xNNNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNNNNNNNNNNNNN
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNNNNNNNNNNKkl;................ .............',:oxxkOO0KKKKKKXXXXXXXXXXXXXXXXXXXXXXXXKKKKKKKKKKKKOdlldkOOOOkxxxxkkkkOOd:xNWNNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNNNNNNNNNNNNN
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNNNNNNNNNNX0dc'.............     ........'',coxxkkO0KKKXXXXXXXXXXXXXXXXXXXXXXXXXXXKKKKKKKKKKKKXKKkdlldxkkkkkkkkkkkkOOd;dNWNNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNNNNNNNNNNNNN
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNNNNNNNNNNXOo;'............     ........':odxkOO0KKXXXXXXXXXXXXXXXXXXXXXXXXXXXXKKKKKKKK0KKKKKKKK0koccloodxxkkxxxxkkOdlxXWNNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNNNNNNNNNNNNN
WWWWWWWWNWWWWWWWWWWWWWWWWWWWNNNWWNNNNNNNNNXKkl;............     ........;oxxkO00KKXXXXNXXXXXXXXXXXXKKKK0000KKXXXKK0KKK0000KKKKKK0kolcclooolodxxxxxOxlco0NNNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNNNNNNNNNNNNN
WWWWWWWNNNNWWWWWWWWWWWWWWWWWNNNWWWNNNNNNNNNNKOo:'..........  ..  ......,loddxk0KKKKXXXNXXXXXKXXXXX0OOOOO00KKKKXXKKK00000000KKKKKKOdlc:cclloxkkddxOxc,,;lOXNNNNNWWWWWWWWWWWWWWWWWWWWWWWWWWWWNNNNNNNNNNNNN
WWWWWWNNNNNNWWWWWWWWWWWWWWWWWWWWWWWNNNNNNNNNNXOdc,..............  ....'cdddxxxk0KKKXXXXXKXXXXXXXKKK000000000KKKKKKKK0000000000KKK0xlc:cloddxxxxkOdc;,',;oKNNWNNWWWWWWWWWWWWWWWWWWWWWWWWWWWWNNNNNNNNNNNNN
WWWWWNNNNNNNNWWWWWWWWWWWWWWWWWWWWWWNNNNNWNNNNNXOdl;,'..........  .....,okOOOkxdxk00KKKXKKXXXKKK00OOOOOOOOOkkkO0KKKKK00000000000000kocclodxxkkxxdc;;::;,,l0NNNWWWNWWWWWWWWWWWWWWWWWWWWWWWWWWNNNNNNNNNNNNN
WWWWWNNNNNNNWWWWWWWWWWWWWWWWWWWWWWWWNNNNNNNNNNNX0Odc;'................,oxxxkkkxddxxxOKKKKXXKKK0OkOOOOkkkxxxxxkkk0KKKK000KK00O0000Oxo:::codddl:,;:::c:;,,cONNNNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNNNNNNNNNNNNN
WWWWWNNNNNNNWWWWWWWWWWWWWWWWWWWWWWWWWWWNNNNNNNNNNNKOd:'...............,cdkO00000OkxoldOKKKKKKK0xk0OxxkO000000Okxk0KKKKKKKKK0000KK0kolcodkxxkd:,,;cc:;::,c0WWNNWWNWWWWWWWWWWWWWWWWWWWWWWWWWWNNNNNNNNNNNNN
WWWWWNNNNNNNWWWWWWWWWWWWWWWWWWWWWWWWWWWWNNNNNNNNNNNNKxl:,............';lxxxxdxOOOOOkl:o0KKKKKK0xxkkxxxxxxddkOOOOxk0KKKKKKKKK0KKKK0kddxkkkxxxkkc'';lolc;;xNNNNWWNWWWWWWWWWWWWWWWWWWWWWWWWWWWNNNNNNNNNNNNN
WWWWWNNNNNNNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNNNNNNNNNNNX0kdc;,'.........,:col:;:odxxool:o0KXKKKXKkoddlcloxo::llllxOkkO0KKKKKKKKKKKK0kxxkOOkkkxdxxc;,,,,,;xXNNNNNNNWWWWWWWWWWWWWWWWWWWWWWWWWWWNNNNNNNNNNNNN
WWWWNNNNNNNNNNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNNNNNNNNNNNNXK0Oxl,'',;,'';:lddlolloxkxolcxKKXXXXXXKkxxdooxkxooodoodO00000K000KKKKKKK0kxxO0KK000kxxl,...';xXNNNNNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNNNNNNNNNNNNN
WWWNNNNNNNNNNNNNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNNNNNNNNNNNNNNKkdxxkkdc:cldxxddxxkkxdloOKKKXXXXXXKOkkkkkkkkkkOkO00KKK0000000KKKKKK0OOOkkO0KKK0x:.....,dXNNNNNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNNNNNNNNNNNNN
WWWNNNNNNNNNNNNNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNNNNNNNNNNNNNNXNNN0dlloxxkkkOOkxdold0KKKKXXXXKK0OkkkkkOO000KKKXXXXKK000000KKKKK000OxdxkOO00l.....'oKNNNNNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNNNNNNNNNNNNN
WWWNNNNNNNNNNNNNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNNNNNNNNNNNNNNNNNNXKkoxOO0KK000OkxddOKKXKKKXXXXXKK000OOO000KKKXXXXXXKK0000KK00KKK00OxO0OOk00:....'oKNNNNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNNNNNNNNNNNNN
WWWWWWWWWNNNNNWWWWWWWWWNNNNWWWWWWWWWWWWWWWWWWNNNWWNNNNNNNWNNNNNNNNNNKkdk0KXXXKK0OkxxOKKXKKKKKKXXXKKKKKKKKKKKKXXXXXXXXKK0000K000KKKKK0O0XK000x,...'dKNNNNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNNNNNNNNNNNNN
WWWWWWWWWWWWWWWWWWWWWWWNNNNNNNWWWWWWWWWWWWWWNNNNWWWWWWWNNNNNNNNNNNNNKkxk0KXXXXK0OxxOKXXXXKKKKKKXXKKKKKKXXXXXXXXNXXXXKKK00K0000KKKKXXKKXXXX0d;....lKNNNNNNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNNNNNNNNNNNNN
WWWWWWWWWWWWWWWWWWWWWWWNNNNNNNNNWWWWWWWWWWWWNNNNWWWWWWWNNNNNNNNNNNNNKxdO0KXXXK0OdldOKKXXXKKK00KXX0OO00KKXXXNNNXXXXXKKKKKKK00KKKKKKKKKKKK0x:'....:ONNNNNWNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNNNNNNNNNNNNN
WWWWWWWWWWWWWWWWWWWWWWWWNNNNNNNNWWWWWWWWWWWWNNNNWWWWWWWNNNNNNNNNNNNNKxdkO0KKK0ko;:lxkkO0Okxxocok0OO000O0KXXXXXXXXKKKKKKKKKKKKKKKK00000Oxc'......lKNNNNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNNNNNNNNNNNNN
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNNNWWWNWWWWWNNNNNNNNNNNNNNNNXkdxkO000Odc,,;:ldxkxxkOOkOO00KXX0OkO0KKKXKKKKKKKKKKKKKXXXXKkddk0KOc'......'oKNNNNWWNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNNNNNNNNNNNNNNN
WWWWWWWWWWWWWWWWWWWWWWWWNNNNNNNNNNWWWWWWNNNNWWWWWWWNNNNNNNNNNNNNNNNNXOddxkO00OxocccclddxkO00KKKXXXXXXX0OkkOO00000000KKKXXKKXXXXOxxocoxl'........oKNNNNWWNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNNNNNNNNNNNNNNNN
WWWWWWNNWWWWWWWWWWWWWWWNNNNNNNNNNNNNNWWNNNNNWWWWWWWNNNNNNNNNNNNNNNNNNKkodxxkOOkxdodxkO00000KKKXXXXXXXXKK0kxdxkkOOOOO0KKKXXKKKKKkdxdlol'..... ...oXNNNNNWNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNNNNNNNNNNNNNNNN
WWWWWNNNWWWWWWWWWWWWWWWNNNNNNNNNNNNNNNNNNNNNWWWWWWWNNNNNNNNNNNNNNNNNNNKddxxxxxxdddkOO00KKKKXXXXXXXXKKKKKK0OxooxO00000KKKKKKKKKOocloxd,..........dXNNNNNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNNNNNNNNNNNNNNNN
WWWWNNNNWWWWWWWWWWWWWWWNNNNNNNNNNNNNNNNNNNNNNNNWWWNNNNWNNNNNNNNNNNWNNNXkdkkkkxdoloxkkO0KXXXXKKKKKK0OOOOOkO00xkOOKKK0KKKKKKKK0OdlcoxOo..........;kXNNNWWWNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNNNNNNNNNNNNN
WWWNNNNNWWWWWWWWWWWWWWWNNNNNNNNNNNNNNNNNNNNNNNNNWNNNNNWNNNNNNNNNNNNNNNNKxdkOOxdlc::;cldxkkkkkkkkOOOO00000OO00KKKKKKKKKKKKXK0OkkxkkOOo..... ...'dXNNNNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNNNNNNNNNNNNN
WWWNNNNNWWWWWWWWWWWWWWWNNNNNNNNNNNNWNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN0dxkkxkdc:::codxxkkkO0000KKKKKKKKK00XKKKKKKKKKKKXK0OOOO00OOkc.....  .'l0NNNNNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNNNNNNNNNNNNN
WWWNNNNNWWWWWWWWWWWWWWWNNNNNNNNNNNWWWNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNXOddxxxdlclodkkkkkkO0KK0KKXXXXXXKKK0XXKKKKKKKKKKK0OOOO000OOOl......'ckKNNNNNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNNNNNNNNNNNNN
WWWWWWWWNNNNWWWWNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWWWWNNNNNNNNNNNNNNXOddxxdooxkkOOOkkOO00KKXNNNNNXXK0KKXXXKKKKK0000O000O000OO00x;..,:ldkKNNNNNNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNNNNNNNNNNNNN
WWWWWWWWNNNNNWWWNNNNNNNNNNNNNNNNNNWWNNNNNNNNNNNNNNNNNNWWWWWNNNNNNNNNNNNNNNXOdddddxO000KKKKXXXKXXNNNNNNXXKKKKKKKKKK00OOOO0K0OO000OO0KOl;,;ldk0XNWNNNNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNNNNNNNNNNNNN
WWWWWWWWNNNNNNWNNNNNNNNNNNNNNNNNWWWWWNNNNNNNNNNNNNNNNNWWWWWNNNNNNNNNNNNNNNNX0xddxO0KKKXXXXXXXXXNNNNNXXXXXKKKKKKK00OkkO0KK0000K0OkOKKOlclldOXNNNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNNNNNNNNNNNNN
WWWWWWWNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWWWWWNNNNNNNNNNNNNNNNNNXOddk00KKKXXXXXXXXNXXXXXXKKK000000OkkkO0KKKK00KKK0OO00kdok00XNNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNNNNNNNNNNNNN
WWWWWWWWNNNNNWNNNNNNNNNNNNNNNNNNNNWWWNNNNNNNNWWWNNNNNNWWWNNNNNNNNNNNNNNWNNNNNNNKkxxk0000KKKKXXXXXKKKKK00OOOkkkkkkO0KKKKKKKKKK00OOOkkOdkNWWWNWWNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNNNNNNNNNNNNN
WWWWWWWWNNNNWWNNNNNNNNNNNNNNNNNNNNWWWNNNNNNNWWWWNNNNNNNWWWNNNNNNNNNNNNNNNNNNNNNNXKOkxxxkkOOOOOOOkkkOkkkxxxxxkkkO0KKKKKKKKKK000OkO0KK0xdOKXNWWNWWNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNNNNNNNNNNNNN
WWWWWWWWNNNNWWNNWWWWWWWWWNNNNNNNNNWWWNNNNNNNNNWWNWWWWWNWWWNNNNNNNNNNNNNNNNNNNNNNNXNKkoclooooodddddkkxxdxxxkkOOO00KKKKKKKK00OOO00KKK0kdc:coOXNNWWNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNNNNNNNNNNNNN
WWWWWWWWNNNNWWNNWWWWWWWWWWNNNNNNNNWWWNNNNNNNNNNWWWNNNWWWWWNNNNNNNNNNNNNNNNNNNNNNNNNNKd;:loollddddxkkxxxkkkOOkOO00KKKKK00OOOO0KKKK0Oxxkd:,,:dKNNNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNNNNNNNNNNNNN
WWWWWWNWWNNWWWWWWWWWWWWWWNNNNNNNNNNWWWNNNNNNNWWWWNNNNNWWWWNNNNNNNNNNNNNNNNNNNNNNNNNNKd;,cddolcoxxkkkkkkOOOOOOO00000000OOOO0KKKKK0ko:;ccc:;,;o0NNWWNNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNNNNNNNNNNNNN
WWWWWNNNWWWWWWWWWWWWWWWWNNNNNNNNNNNNWWWWWWWWWWWNNNNNNNNWWWWNNNNNNNNNNNNNNNNNNNNNNNNXOo:,':dxxdodkkOOOO00000OO000000OOOOO0KXXK000OOdc;,'.',;lkO0NNNNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNNNNNNNNNNNNN
WWWWWNNNWWWWWWWWWWWWWWWWNNNNNNNNNNNNWWWWNNNNNNNNNNNNNNNNWNNNNNNNNNNNNNNNNNNNNNNNNXXXkll:'':dkkxdxkOO00KKKK000KK0OOOOOOOKKKKKKOo;:lolc:,..:xOk00O0NNWNNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNNNNNNNNNNNNN
WWWWWNNNWWWWWWWWWWWWWWWWNNNNNNNNNNNNWWWNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNX0xllc:,':dkkdddkOO0KXXKK0KKK0O000KK00O00Od:'.'....';,;ldodO0kddOXNNNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNNNNNNNNNNNNN
WWWWWWNNNNWWWWWWWWWWWWWWNNNNNNNNNNNNNNNNWNNNNNNNNNNNNNNNWNNWNNNNWNNNNNNNNNNNNNXNX0xccclolc::cdxdoodkO00KXKK000000KKXXK0000ko:;,'.';cc::dx:..:loxdcox0NNNNNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNNNNNNNNNNNNN
WNNNNNNNNNNWWWWWWWWWWWWWNNNNNNNNWWNNNNNNNNNNNNNNNNNNNNNNNNNWNNNNNNNNNNNNNNNNNXX0xc,';lllodxdddxxoodkOO0OO0OO000000K00000ko:',;;;',cdkxoxkl..,clc::loxkOKXNNNNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNNNNNNNNNNNNN
NNNNNNNNNNNWWWWWWWWWWWWNNNNNNNNNWWWWNNNNNNNNNNNNNNNNNNNNNNNNNNXNNNNNNNNNNXXKOxl:,'.,cllododkOOkkkkkkkOOkkOO0KKOkkO000K0xl;''''.,;,:oko,ckx;.:c,:cloddodkO0KXXNNWWWWWWWWWWWWWWWWWWWWWWWWWWWWNNNNNNNNNNNNN
WWWWWNNNNNNWWWWWWWWWWWWNNNNNNNNNNNNNNNNNNNNNNNNXKKXK0KK00OkkxxdddddxOKX0xol:;,.....;olclddodxxxkkkkxxxkkkkkkkxxkOKKKKKOdl;';:,,,,.',lc,,col::;:oooodddxxxkkOO0XNNNNWWWWWWWWWWWWWWWWWWWWWWWWNNNNNNNNNNNNN
WWWWWWWWNWWWWWWWNNNNNNNNNNNNNNNNNNNNNNNNNNNNXKkxdddollodol:::::cc;,,:ooc,''',,'''..:ddl:okdoollllooooodddddxkO0KXXKO0Kklo:';;;c:',;;,',;clcclodddddddodxxxxkOkkOKXNWWWNNNNWWWWWWWWWWWWWWWWWWNNNNNNNNNNNN
WWWNNNWWWWWWWWWNNNNNNNNNNNNNNNNNNNNNNNNNNXK0kdocccclc;;cl::::::;;;;:::;,''''',,,,..:odoccdkkxdolclloodxxkkO000XXXXK0O0kodo;;:;:;;:c:,;coddoddoooldxdddxxxxxkkxkkxxOKXXNXNNNNNWWWWWWWWWWWWWWWNNNNNNNNNNNX
WWNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNXKOdolllc::c:;,,;:;::;,,',::lc:;,''...',:ooodkkkdlcldOOOxdkO00000KK000KXXXXKK00xoddc;;c:;:::;:odddddxdooddkkkxkxddxkkkxxxddxkkOOOOOKKXXXXXNWWWWWWWWNNNNNNNNNNNNNX
WNNNNNNNNNNNNNNNNNNNNNNNWWWWWWWNNNNNNNXKkoolccclc:::;,,,;;;;,'';::,;:::;,....,oO00000K000OxdxOOOkOKXXXK0000KKKKK00Okkkxccol;,;;;;:lodxxxxxkOkddxxxxxddoodxxxxxxxxxkkxkkkkkO000KKKKXXNNWNNNNNNNNNNNNNNNNX
WWNNNNNNNNNNNNNNNNNNNNNNWWWWNNNNNNNNNNXkddlccclollc::::;;,,'';:cc:;,,,,,...',o0K0O0KKK0KK00OOOO000KKKKK000KKKKKK00OxxOklclccloddxdddxxkxxdddddooddddoloxkxxxxxkkkxxxxkkOO00KKKKKKKXXXKXNNNNNNNNNNNNNNNNN
WWNNNNNNNNNNNNNNNNNNNNNNWWNNNNNNNNNNNKkoddlcoooooc:::cc;'''';cllc::;;;,...,;oO00000KKKKK00OO0KKK00KKKKXXKKKK0KXXK0OkOxc::,'',;cdddxxxkOOkkxdxxxdxxdolldOOkxxkkkkxxxkkkOO0000KKKKXXXXNNXXNWNNNNNNNNNNNNNN
WWNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNXKkoodl:coolllc:::cc;'',:clllc;;;;;,..':ok000000KK0OO0000000OO0KKKKKKKKKKKKKKOkkOxllc;''''.'lddxxdxO00OxdxkxdxxxdlldkOkxxkkkkkkkOOO00000KKKKXXXXXXNNXXNNNNNNNNNNNNNNN
WWNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNXOxddoc;colcloolcccc;',:llcccc:;;;:,..:dkO00000KKOOO00Odoooold00OO0KXKKKKKK0OkOOxkOd;'''',''lxxxxddxkOOxddxxddxkxoccoxkkOOOkkkkkOO00KKKKKKXXXXXXNNNNXXXXNNWNNNNNNNNNN
WWNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNXX0xxko:;cllolllllc:,,;coocccccc:;::;,:okO00OOkO0OkxxkkxddxxolokOOO0KKKKK0KK0OOkdxOxo:,;,.',:okkxddooxxxxxxxxkkxxxo:cdkkkkOOOOOOOOO0KKKKXXXXXNNNXXXNNNNNXXNNNNNNNNNNNN
WWNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNXKOxkkl;;:lodolllc:;';codoc::cccc:,'.,lxxxkOOkkxxxxxdxOkk0OOkxookO000KKKK0K0kOkdxOxc,,;cc;lddxxkxdolldddxkkkkOkxxxdcoxO0OkkOOOOOO000KKKXXXXXNNNNNXXXNNNNNXXNNNNNNNNNNN
WWNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNXK0kkxl;:lllolloc;;,,:looc;;:ccc;'..'cxkkxxkxdddxkOOkOKOO0OkOOxllxO0000KXXKOxdoxOOl'',,,:dxxxOOOkxolldxxxxkOkkxxOOxooxO00OOO000000KKXXXXXXXXNNNNNNNNNNNNNNXXNNNNNNNNNN
WWNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNXXK0kxdl;:llooooc;,,;cllc:;;;clc;...':xkOklcoodkxk00OO00OOK0OOkxdc:co0K0O0Kx:,:x0Ol'':ll:;oxxkkkOOOxooxkkOOOkxxkkkOxlcokOO00000000KKXXXXXXXXXXNNNNNNNNNNNNWNNNNNNNNNNNN
WWNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNXXX0xool::looddoc,',lolc:,,:clc'....'lOOOkc:odkOO0KOOOK0OOKKOkxxxl,.;ok000Ol';oOkl'..',,,;oxkkkxxxxdodkO00OOxdxOOkkxooxO000000000KKXXXXXXXXXNNNNNNNNWWNNWNNWNNNNNNNNNNN
WWNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNXXX0xxxdc:lloool:',ldoc:;;:cll;.....,d0O0kc:oxxk0K0Ok0K0kOK0OkxOkc;;coxOOOOxdkOx:. ....'',:oxkkkxxolokO00OkxdxOOOOOOkxk0KKKKKKKKKXXXXXXXXNNNNNNNNWWWWWNNNNNNNNNNNNNNNNN
WWNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNXK0kO0kl:cloooc;,coolc:;:ccllc,...'ck00k:,cdxkO0K000KKOk0K0OOO0klldxxkO00OO0kl'..,:;'.''.'cdOOkkxxdxk00OkxdkOOOkkOOOkk0KKKKKKKKXXNXXXNNNNNNNNWWWNNNNNWWNNNNNNNNNNNNNNN
WWNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNXX0kkOxocclddo:,cllcccc::cccc:,..,cxO0O:.,xkkO0K000KKKOkOKK00OOdlxkkO000000Oo'.,;:c:,....,okOOkkkkkkxkkOkkkkOOOkOO0OkOKXKKKKKXXNNNNNNNNNNNNWWWWWWNNWWWWNNNNNNNNNNNNNNN
WNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNKOOOkkollool:coolllolcc:::;'...;dO00Ol;dOkO0KK0000KK0OOKK00OOdokkOKK00KKOd,';c,..',''''lkkOOxxxkOkxxkOOkkOOOOOO0000KXXXXXNNNNNNNNNWWWWWWWWWWWWWWWWWWWNNNNNNNNNNNNNNN
NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNK0OOOxoool:codooooooolc:;,'...ck000Okk0OO0KXK000KK0OO0K0O00kdxOO0K0OKK0xc';c,.'..:l:,ckOOOOkxxkkkxkOOOOOOOOO00KKXXNNNNNNNWWNNNWWWWWWWWWWWWWWWWWWWWWNNNNNNNNNNNNNNNX
NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNXKK00Oxxdccoddddoooooooc;'...;d000kdx00OOKXKK000KK00000OO00kxk00K0O0K00d;';:..,,,clcoxO0OOkxkkOOO0000KK00000KKXXNNNNNNNNWWWWWWWWWWWWWWWWWWWWWWWWWWWNNNNNNNNNNNNNNNX
NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNXXXKOkxddxxxxxddodddddc'..'lO0KOddO000KXKK00KKX0OOO00kO00kkO0KKO0K000Oc''::,...:c;ck0000kkkk0KXKKXXXXKKKKXXXNNNNNNNNNWWWWWWWWWWWWWWWWWWWWWWWWWWWWNNNNNNNNNNNNNNNX
WWWNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNXXK0OOOOOOOOkdddxxkko:'.;xKKXKO0KKKKKK0000KKK0kkO0OkO00kk0KK00000000d;.';;,,;cldk0KK00OO00KXXXXXXXXXXXNNNNNNNNNNWWWWWWWWWWWWWWWWWWWWWWWWWWWWNNNNNNNNNNNNNNNNNNX
WWWNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNXXK0000K00Oxxxxkkkxc''o0XXX00KKKK00KK00K0KK0OO0K0O000kOKK00KKK0K00d;''..;lxO0KKKKK00000KXXXXXXXNNNNNNNNNNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNNNNNNNNNNNNNNNNNNNX
WWWNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNXXKKXXKK0OkkkkkkOd,:OXXXKO00KKKXKKXKKKKKK0OO0KK0000O0KKKKKKKK0d:,',;':kKKKKKKKKK000KKXXXNNNNNNNNNNNNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNNNNNNNNNNNNNNNNNNNX
WWWNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNXXXXKKK00O000K0xOXXNKO0KKKXXNXXNXXXNNXXX0OKXXKK0KKO0XXXXXXo..',:c,;kXXXXXXKKKKKKXXNNNNNNNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNNNNNNNNNNNNNNNNNNNX
NNNNNNNNNWWNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNXXXXXXXXXXXXXNXNNNNXKKKKXNNNNNNNNNNNNNNNNXXXXXNKxdKNNNXNO,.cdxOOdlkXXXXXXXXXXXXNNNNNNNWWNNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNNNNNNNNNNNNNNNNNNNNNX
NNNNNNNNNWWNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNXXXXXXXXXNNNNNNNNNNNNKKXNNNNNNNNNNNNNNNNNNNNNNNKkONWNXXNkck00XXXXXXXXNNXXNNNNNNNNNNNNNNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNNNNNNNNNNNNNNNNNNNNNNNX
NNNNNNNNNWWNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNXKXNNNNNNNNNNNNNNNNNNNNWWWWWNNNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNNNNNNNNNNNNNNNNNNNNNNNX
NNNNNNNNNWWNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNNNNNNNNNNNNNNNNNNNNNNNX
NNNNNNNNNWWNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWNNNNNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNNNNNNNNNNNNNNNNNNNNNNXX
NNNNNNNNNWWNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNNNNNNNNNNNNNNNNNNNNNNXX
NNNNNNNNNWWNNNNNNNNNNNNWWWNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNNNNNNNNNNNNNNNNNNNNNNNX
NNNNNNNNNWWNNNNNNNNNNNNWWWNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNNNNNNNNNNNNNNNNNNNNNNNX
NNNNNNNWNNNNNNNNNNNNNNNWWWNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWWWWWNNNNNNNNNNNNWWNNNNNNNNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNNNNNNNNNNNNNNNNNNNNNNNX
NNNNNNNNNNNNNNNNNNNNNNNNWWNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWNNNNNNNNNNNNNNNNWWWWWWNNNNNNWWWWWWWWNNNNNNNNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNNWWWWWWWWNNNNNNNNNNNNNNNNNNNNNNNX
NNNNNNNNNNNNNNNNNNNNNNNNWWNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWWWWWNNWWWWWWWNNNNWWWWWWWNNNNNNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNNNNNNWWWWWWWNNNNNNNNNNNNNNNNNNNNNNNX
NNNNNNNNNNNNNNNNNNNNNNNNWWNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNNNNNNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNNNNNNNNWWWWWWWNNNNNNNNNNNNNNNNNNNNNNNX
NNNNNNNNNNNNNNNNNNNNNNNWWWWNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNNNNNNWWWWWWNWWWNNNWWWWWWWNNNNNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNNNNNWWWWWWWNNNNNNNNNNNNNNNNNNNNNNNX
NNNNNNNNNNNNNNNNNNNNNNNWWWWWNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNNNNNNNWWWWNNNWNNNNNWWWWWNNNNNNNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNXX
NNNNNNNNNNNNNNNNNNNNNNNNWWWWWNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWWNNNNNNNWWWWWWWWWNNWWWWWWNNNNWWWNNNWWWWNNNWNNNNNWWWWWNNNNNNNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNXX
NNNNNNNNNNNNNNNNNNNNNNNNWWWWWWNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWNNNNNNNNNWWWWWWWNNNNWWWWNNNNNWWWWNNWWWWNNNWNNNNNWWWWWNNNNNNNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNXX
NNNNNNNNNNNNNNNNNNNNNNNWWWWWWWWNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWNNNNNNNWWWWWWWWWWWWWWNNNNNWNNNNNNNWNNNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNNWNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNXX
NNNNNNNNNNNNNNNNNNNNNNWWWWWWWWWNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWWWWWWWWWWWNNNNNNNNNNNNNNNNNNNNWWWNNNNNNNNNNNNNNNNNNNNWWWWWWWNNNWNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNXX
WNNNNNNNNNNNNNNNNNNNNWWWWWWWWWWNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWWWWWNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWWNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNXX
WWNNNNNNNNNNNNNNNNNNNWWWWWWWWWWNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWWWNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNXX
WWWWWWWWNNNNNNNNWNNNNWWWWNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNXX
WWWWWWWWNNNNNNNNWNNNNNWWNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNXX

""")

import sys
import distutils.dir_util as dis
import glob
import winsound
import os

version = '0.4.4'
print("")
print("")
print("""

EVERYONE MUST DO THIS THING:

1. Open "My Games" folder in Documents
2. Open "beyond the sword" folder
3. Open CivilizationIV.ini
4. Update the following lines from 0 to 1:

; Disable caching of file system (may slow initialization)
DisableFileCaching = 1

; Disable caching of xml and file system (may slow initialization)
DisableCaching = 1

""")
print("")
print("")
print('Preparing to install DowagerMod version %s, please wait...' % version)
winsound.PlaySound('install_noise.wav',winsound.SND_FILENAME)

## Functions
def findPath(civ_drive):
    """
    Returns either the path where Civ 4 is installed or 'Failed'.
    """
    for root, directories, filenames in os.walk(civ_drive.upper()):
        for directory in directories:
            current_path = os.path.join(root, directory).replace("\n",'\\')
            if "\\Sid Meier's Civilization IV Beyond the Sword" in current_path and "steam" in current_path.lower():  # \\Beyond the Sword\\Assets
                print("""
                ---------------------------------
                Civ 4 BTS Assets Directory found!
                ---------------------------------
                
                {0}
                
                """.format(current_path))
                response = input("Is this the correct directory? [y / n]: ")
                response = response.lower()
                if response == "y":
                    return current_path
                else:
                    pass
    return "Failed"
                
def installMod(civ_directory):
    dis.copy_tree(src_path,civ_path)
    print('Finished installing HarrisonMod version %s!' % version)

## Fetch install path
src_path = sys.argv[0][:-16].replace('/','\\') + "Sid Meier's Civilization IV Beyond the Sword"

# Prompt the user for the drive where they think the game is installed.
civ_drive = input('Type the letter drive name (caps insensitive) where Civ Beyond the Sword is installed (e.g., C): ')
civ_path = findPath(civ_drive + ":\\")
if civ_path == "Failed":
    print("Could not find Assets directory. Installation failed. Goodbye!")
else:
    print("""
    
    Installing DowagerMod to {0}
    
    """.format(civ_path))
    installMod(civ_path)
    exit = input('Success! Click enter to exit setup.')
