directories:
  output: release
  buildResources: build
appId: com.dowagermod.launcher
productName: DowagerMod Installer
files:
  - filter:
      - dist/**/*
      - electron/**/*
extraResources:
  - from: ../CoreFiles/install_for_gui.py
    to: install_for_gui.py
win:
  target: portable
  icon: public/favicon.ico
electronVersion: 29.4.6
